services:
  app:
    build: ./node/
    # entrypoint: dockerize -wait tcp://mysql:3306 -timeout 20s -wait tcp://nginx:8080 -timeout 20s
    volumes:
      - ./node:/usr/src/app
    ports:
      - "3000:3000"
    depends_on:
      - mysql
      - nginx
    networks:
      - node-network

  nginx:
    build: ./nginx/
    ports:
      - "8080:80"
    networks:
      - node-network

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: my_db
      MYSQL_USER: me
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    networks:
      - node-network


networks:
  node-network:
    driver: bridge